import type { AssetInput } from '@pascal-app/core'
export const CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'tesla',
    category: 'outdoor',
    tags: ['floor', 'garage'],
    name: 'Tesla',
    thumbnail: '/items/tesla/thumbnail.webp',
    src: '/items/tesla/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.7, 5],
  },
  {
    id: 'ev-wall-charger',
    category: 'appliance',
    tags: ['wall', 'garage'],
    name: 'Ev-wall-charger',
    thumbnail: '/items/ev-wall-charger/thumbnail.webp',
    src: '/items/ev-wall-charger/model.glb',
    scale: [1, 1, 1],
    offset: [-0.07, 0.4, 0.15],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 0.5],
    attachTo: 'wall',
  },
  {
    id: 'pillar',
    category: 'outdoor',
    tags: ['structure', 'fencing'],
    name: 'Pillar',
    thumbnail: '/items/pillar/thumbnail.webp',
    src: '/items/pillar/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.3, 0.5],
  },

  {
    id: 'high-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'High Fence',
    thumbnail: '/items/high-fence/thumbnail.webp',
    src: '/items/high-fence/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [4, 4.1, 0.5],
  },

  {
    id: 'medium-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'Medium Fence',
    thumbnail: '/items/medium-fence/thumbnail.webp',
    src: '/items/medium-fence/model.glb',
    scale: [0.49, 0.49, 0.49],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 2, 0.5],
  },

  {
    id: 'low-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'Low Fence',
    thumbnail: '/items/low-fence/thumbnail.webp',
    src: '/items/low-fence/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 0.5],
  },

  {
    id: 'bush',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Bush',
    thumbnail: '/items/bush/thumbnail.webp',
    src: '/items/bush/model.glb',
    scale: [0.96, 0.96, 0.96],
    offset: [-0.14, 0.01, -0.13],
    rotation: [0, 0, 0],
    dimensions: [3, 1.1, 1],
  },

  {
    id: 'fir-tree',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Fir',
    thumbnail: '/items/fir-tree/thumbnail.webp',
    src: '/items/fir-tree/model.glb',
    scale: [1, 1, 1],
    offset: [-0.01, 0.05, -0.07],
    rotation: [0, 0, 0],
    dimensions: [0.5, 3, 0.5],
  },

  {
    id: 'tree',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Tree',
    thumbnail: '/items/tree/thumbnail.webp',
    src: '/items/tree/model.glb',
    scale: [0.65, 0.65, 0.65],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    dimensions: [1, 5, 1],
  },

  {
    id: 'palm',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Palm',
    thumbnail: '/items/palm/thumbnail.webp',
    src: '/items/palm/model.glb',
    scale: [0.37, 0.37, 0.37],
    offset: [0, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [1, 4.5, 1],
  },

  {
    id: 'patio-umbrella',
    category: 'outdoor',
    tags: ['leisure', 'floor'],
    name: 'Patio Umbrella',
    thumbnail: '/items/patio-umbrella/thumbnail.webp',
    src: '/items/patio-umbrella/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 3.7, 0.5],
  },

  {
    id: 'sunbed',
    category: 'outdoor',
    tags: ['leisure', 'seating', 'floor'],
    name: 'Sunbed',
    thumbnail: '/items/sunbed/thumbnail.webp',
    src: '/items/sunbed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.04, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1.5],
  },

  {
    id: 'window-double',
    category: 'window',
    tags: ['wall'],
    name: 'Double Window',
    thumbnail: '/items/window-double/thumbnail.webp',
    src: '/items/window-double/model.glb',
    scale: [0.81, 0.81, 0.81],
    offset: [0, -0.32, 0],
    rotation: [0, 3.14, 0],
    dimensions: [1.5, 1.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'window-simple',
    category: 'window',
    tags: ['wall'],
    name: 'Simple Window',
    thumbnail: '/items/window-simple/thumbnail.webp',
    src: '/items/window-simple/model.glb',
    scale: [1, 1, 1],
    offset: [1.06, -0.21, 0.05],
    rotation: [0, 3.14, 0],
    dimensions: [1.5, 2, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'window-rectangle',
    category: 'window',
    tags: ['wall'],
    name: 'Rectangle Window',
    thumbnail: '/items/window-rectangle/thumbnail.webp',
    src: '/items/window-rectangle/model.glb',
    scale: [0.81, 0.81, 0.81],
    offset: [-1.41, -0.28, 0.08],
    rotation: [0, 3.14, 0],
    dimensions: [2.5, 1.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'door-bar',
    category: 'door',
    tags: ['wall'],
    name: 'Door with bar',
    thumbnail: '/items/door-bar/thumbnail.webp',
    src: '/items/door-bar/model.glb',
    scale: [1, 1, 1],
    offset: [-0.48, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'glass-door',
    category: 'door',
    tags: ['wall'],
    name: 'Glass Door',
    thumbnail: '/items/glass-door/thumbnail.webp',
    src: '/items/glass-door/model.glb',
    scale: [0.9, 0.9, 0.9],
    offset: [-0.52, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 0.4],
    attachTo: 'wall',
  },

  {
    id: 'door',
    category: 'door',
    tags: ['wall'],
    name: 'Door',
    thumbnail: '/items/door/thumbnail.webp',
    src: '/items/door/model.glb',
    scale: [0.79, 0.79, 0.79],
    offset: [-0.43, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2, 0.4],
    attachTo: 'wall',
  },

  {
    id: 'parking-spot',
    category: 'outdoor',
    tags: ['leisure', 'floor'],
    name: 'Parking Spot',
    thumbnail: '/items/parking-spot/thumbnail.webp',
    src: '/items/parking-spot/model.glb',
    scale: [0.9, 1, 0.78],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [5, 1, 2.5],
  },

  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Outdoor Playhouse',
    thumbnail: '/items/outdoor-playhouse/thumbnail.webp',
    src: '/items/outdoor-playhouse/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 1],
  },

  {
    id: 'skate',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Skate',
    thumbnail: '/items/skate/thumbnail.webp',
    src: '/items/skate/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.2, 0.5],
  },

  {
    id: 'scooter',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Scooter',
    thumbnail: '/items/scooter/thumbnail.webp',
    src: '/items/scooter/model.glb',
    scale: [1, 1, 1],
    offset: [0.11, 0, 0.17],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 0.5],
  },

  {
    id: 'basket-hoop',
    category: 'outdoor',
    tags: ['leisure', 'sports', 'floor'],
    name: 'Basket Hoop',
    thumbnail: '/items/basket-hoop/thumbnail.webp',
    src: '/items/basket-hoop/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.8, 1],
  },

  {
    id: 'ball',
    category: 'outdoor',
    tags: ['leisure', 'sports', 'floor'],
    name: 'Ball',
    thumbnail: '/items/ball/thumbnail.webp',
    src: '/items/ball/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.12, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'wine-bottle',
    category: 'kitchen',
    tags: ['countertop', 'decor'],
    name: 'Wine Bottle',
    thumbnail: '/items/wine-bottle/thumbnail.webp',
    src: '/items/wine-bottle/model.glb',
    scale: [1, 1, 1],
    offset: [-0.05, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 0.5],
  },

  {
    id: 'fruits',
    category: 'kitchen',
    tags: ['countertop', 'decor'],
    name: 'Fruits',
    thumbnail: '/items/fruits/thumbnail.webp',
    src: '/items/fruits/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'cutting-board',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Cutting Board',
    thumbnail: '/items/cutting-board/thumbnail.webp',
    src: '/items/cutting-board/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
  },

  {
    id: 'frying-pan',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Frying Pan',
    thumbnail: '/items/frying-pan/thumbnail.webp',
    src: '/items/frying-pan/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 1],
  },

  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Kitchen Utensils',
    thumbnail: '/items/kitchen-utensils/thumbnail.webp',
    src: '/items/kitchen-utensils/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
  },

  {
    id: 'microwave',
    category: 'kitchen',
    tags: ['countertop', 'electronics'],
    name: 'Microwave',
    thumbnail: '/items/microwave/thumbnail.webp',
    src: '/items/microwave/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [1, 0.3, 0.5],
  },

  {
    id: 'stove',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Stove',
    thumbnail: '/items/stove/thumbnail.webp',
    src: '/items/stove/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
  },

  {
    id: 'fridge',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Fridge',
    thumbnail: '/items/fridge/thumbnail.webp',
    src: '/items/fridge/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, -0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'hood',
    category: 'kitchen',
    tags: ['wall'],
    name: 'Hood',
    thumbnail: '/items/hood/thumbnail.webp',
    src: '/items/hood/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1, 1.1],
    attachTo: 'wall-side',
  },

  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    tags: ['wall', 'storage'],
    name: 'Kitchen Shelf',
    thumbnail: '/items/kitchen-shelf/thumbnail.webp',
    src: '/items/kitchen-shelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1, 1.1],
    attachTo: 'wall-side',
  },

  {
    id: 'kitchen-counter',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage'],
    name: 'Kitchen Counter',
    thumbnail: '/items/kitchen-counter/thumbnail.webp',
    src: '/items/kitchen-counter/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 1],
    surface: {
      height: 0.75,
    },
  },

  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage'],
    name: 'Kitchen Cabinet',
    thumbnail: '/items/kitchen-cabinet/thumbnail.webp',
    src: '/items/kitchen-cabinet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 1],
    surface: {
      height: 1.1,
    },
  },

  {
    id: 'kitchen',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Kitchen',
    thumbnail: '/items/kitchen/thumbnail.webp',
    src: '/items/kitchen/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1.1, 1],
  },

  {
    id: 'toilet-paper',
    category: 'bathroom',
    tags: ['wall', 'decor'],
    name: 'Toilet Paper',
    thumbnail: '/items/toilet-paper/thumbnail.webp',
    src: '/items/toilet-paper/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.19, 0.12],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'wall-side',
  },

  {
    id: 'shower-rug',
    category: 'bathroom',
    tags: ['floor', 'decor'],
    name: 'Shower Rug',
    thumbnail: '/items/shower-rug/thumbnail.webp',
    src: '/items/shower-rug/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.1, 0.5],
  },

  {
    id: 'laundry-bag',
    category: 'bathroom',
    tags: ['floor'],
    name: 'Laundry Bag',
    thumbnail: '/items/laundry-bag/thumbnail.webp',
    src: '/items/laundry-bag/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 0.5],
  },

  {
    id: 'drying-rack',
    category: 'bathroom',
    tags: ['floor'],
    name: 'Drying Rack',
    thumbnail: '/items/drying-rack/thumbnail.webp',
    src: '/items/drying-rack/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 1],
  },

  {
    id: 'washing-machine',
    category: 'bathroom',
    tags: ['floor', 'large', 'electronics'],
    name: 'Washing Machine',
    thumbnail: '/items/washing-machine/thumbnail.webp',
    src: '/items/washing-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
  },

  {
    id: 'toilet',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Toilet',
    thumbnail: '/items/toilet/thumbnail.webp',
    src: '/items/toilet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.23],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 1],
  },

  {
    id: 'shower-square',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Squared Shower',
    thumbnail: '/items/shower-square/thumbnail.webp',
    src: '/items/shower-square/model.glb',
    scale: [1, 1, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'shower-angle',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Angle Shower',
    thumbnail: '/items/shower-angle/thumbnail.webp',
    src: '/items/shower-angle/model.glb',
    scale: [1, 1, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'bathtub',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Bathtub',
    thumbnail: '/items/bathtub/thumbnail.webp',
    src: '/items/bathtub/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1.5],
  },

  {
    id: 'bathroom-sink',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Bathroom Sink',
    thumbnail: '/items/bathroom-sink/thumbnail.webp',
    src: '/items/bathroom-sink/model.glb',
    scale: [1, 1, 1],
    offset: [0.11, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 1.5],
  },

  {
    id: 'ceiling-fan',
    category: 'appliance',
    tags: ['ceiling', 'climate'],
    name: 'Ceiling fan',
    thumbnail: '/items/ceiling-fan/thumbnail.webp',
    src: '/items/ceiling-fan/model.glb',
    scale: [1, 1, 1],
    offset: [-0.12, 0.49, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 1.5],
    attachTo: 'ceiling',
    interactive: {
      effects: [
        {
          kind: 'animation',
          clips: {
            on: 'On',
          },
        },
      ],
      controls: [
        {
          kind: 'toggle',
        },
      ],
    },
  },

  {
    id: 'electric-panel',
    category: 'appliance',
    tags: ['wall', 'electrical'],
    name: 'Electric Panel',
    thumbnail: '/items/electric-panel/thumbnail.webp',
    src: '/items/electric-panel/model.glb',
    scale: [0.61, 0.74, 0.7],
    offset: [0, 0, 0.06],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1, 0.3],
    attachTo: 'wall-side',
  },

  {
    id: 'sprinkler',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Sprinkler',
    thumbnail: '/items/sprinkler/thumbnail.webp',
    src: '/items/sprinkler/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.45, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'ceiling',
  },

  {
    id: 'smoke-detector',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Smoke Detector',
    thumbnail: '/items/smoke-detector/thumbnail.webp',
    src: '/items/smoke-detector/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.49, 0],
    rotation: [Math.PI, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'ceiling',
  },

  {
    id: 'fire-detector',
    category: 'appliance',
    tags: ['wall', 'safety'],
    name: 'Fire Detector',
    thumbnail: '/items/fire-detector/thumbnail.webp',
    src: '/items/fire-detector/model.glb',
    scale: [0.9, 1.4, 0.7],
    offset: [0.02, 0.05, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.3],
    attachTo: 'wall',
  },

  {
    id: 'exit-sign',
    category: 'appliance',
    tags: ['wall', 'safety'],
    name: 'Exit Sign',
    thumbnail: '/items/exit-sign/thumbnail.webp',
    src: '/items/exit-sign/model.glb',
    scale: [0.6, 0.5, 0.7],
    offset: [0, 0.04, 0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.3],
    attachTo: 'wall-side',
  },

  {
    id: 'hydrant',
    category: 'appliance',
    tags: ['floor', 'safety'],
    name: 'Hydrant',
    thumbnail: '/items/hydrant/thumbnail.webp',
    src: '/items/hydrant/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 1],
  },

  {
    id: 'alarm-keypad',
    category: 'appliance',
    tags: ['wall', 'safety', 'electrical'],
    name: 'Alarm Keypad',
    thumbnail: '/items/alarm-keypad/thumbnail.webp',
    src: '/items/alarm-keypad/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
  },

  {
    id: 'thermostat',
    category: 'appliance',
    tags: ['wall', 'climate', 'electrical'],
    name: 'Thermostat',
    thumbnail: '/items/thermostat/thumbnail.webp',
    src: '/items/thermostat/model.glb',
    scale: [2.08, 2.1, 2.59],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.1],
    attachTo: 'wall-side',
  },

  {
    id: 'air-conditioning',
    category: 'appliance',
    tags: ['wall', 'climate'],
    name: 'Air Conditioning',
    thumbnail: '/items/air-conditioning/thumbnail.webp',
    src: '/items/air-conditioning/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.37, 0.21],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 0.9],
    attachTo: 'wall-side',
  },

  {
    id: 'ac-block',
    category: 'appliance',
    tags: ['floor', 'climate'],
    name: 'AC block',
    thumbnail: '/items/ac-block/thumbnail.webp',
    src: '/items/ac-block/model.glb',
    scale: [0.79, 0.79, 0.79],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.1, 1, 1.1],
  },

  {
    id: 'toaster',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Toaster',
    thumbnail: '/items/toaster/thumbnail.webp',
    src: '/items/toaster/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'sewing-machine',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Sewing Machine',
    thumbnail: '/items/sewing-machine/thumbnail.webp',
    src: '/items/sewing-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.7, 0.5],
  },

  {
    id: 'kettle',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Kettle',
    thumbnail: '/items/kettle/thumbnail.webp',
    src: '/items/kettle/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'iron',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Iron',
    thumbnail: '/items/iron/thumbnail.webp',
    src: '/items/iron/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'coffee-machine',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Coffee Machine',
    thumbnail: '/items/coffee-machine/thumbnail.webp',
    src: '/items/coffee-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'television',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Television',
    thumbnail: '/items/television/thumbnail.webp',
    src: '/items/television/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 0.5],
  },

  {
    id: 'computer',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Computer',
    thumbnail: '/items/computer/thumbnail.webp',
    src: '/items/computer/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.5],
  },

  {
    id: 'stereo-speaker',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Stereo Speaker',
    thumbnail: '/items/stereo-speaker/thumbnail.webp',
    src: '/items/stereo-speaker/model.glb',
    scale: [1, 1, 1],
    offset: [0.02, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.1, 0.5],
  },

  {
    id: 'threadmill',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Threadmill',
    thumbnail: '/items/threadmill/thumbnail.webp',
    src: '/items/threadmill/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1.5, 1],
  },

  {
    id: 'barbell-stand',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Barbell Stand',
    thumbnail: '/items/barbell-stand/thumbnail.webp',
    src: '/items/barbell-stand/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1.3, 2],
  },

  {
    id: 'barbell',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Barbell',
    thumbnail: '/items/barbell/thumbnail.webp',
    src: '/items/barbell/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 2],
  },

  {
    id: 'toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'decor'],
    name: 'Toy',
    thumbnail: '/items/toy/thumbnail.webp',
    src: '/items/toy/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
  },

  {
    id: 'car-toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'decor'],
    name: 'Car Toy',
    thumbnail: '/items/car-toy/thumbnail.webp',
    src: '/items/car-toy/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 1],
  },

  {
    id: 'easel',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Easel',
    thumbnail: '/items/easel/thumbnail.webp',
    src: '/items/easel/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.3, 1],
  },

  {
    id: 'pool-table',
    category: 'furniture',
    tags: ['floor', 'leisure'],
    name: 'Pool table',
    thumbnail: '/items/pool-table/thumbnail.webp',
    src: '/items/pool-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1, 4],
  },

  {
    id: 'guitar',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Guitar',
    thumbnail: '/items/guitar/thumbnail.webp',
    src: '/items/guitar/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.2, 0.5],
  },

  {
    id: 'piano',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Piano',
    thumbnail: '/items/piano/thumbnail.webp',
    src: '/items/piano/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.5, 1],
  },

  {
    id: 'round-carpet',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Round Carpet',
    thumbnail: '/items/round-carpet/thumbnail.webp',
    src: '/items/round-carpet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.1, 2.5],
  },

  {
    id: 'rectangular-carpet',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Rectangular Carpet',
    thumbnail: '/items/rectangular-carpet/thumbnail.webp',
    src: '/items/rectangular-carpet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [3, 0.1, 2],
  },

  {
    id: 'cactus',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation'],
    name: 'Cactus',
    thumbnail: '/items/cactus/thumbnail.webp',
    src: '/items/cactus/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 0.5],
  },

  {
    id: 'small-indoor-plant',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation'],
    name: 'Small Plant',
    thumbnail: '/items/small-indoor-plant/thumbnail.webp',
    src: '/items/small-indoor-plant/model.glb',
    scale: [1, 1, 1],
    offset: [-0.01, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.7, 0.5],
  },

  {
    id: 'indoor-plant',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation'],
    name: 'Indoor Plant',
    thumbnail: '/items/indoor-plant/thumbnail.webp',
    src: '/items/indoor-plant/model.glb',
    scale: [1, 1, 1],
    offset: [-0.05, 0, 0.07],
    rotation: [0, 0, 0],
    dimensions: [1, 1.7, 1],
  },

  {
    id: 'ironing-board',
    category: 'furniture',
    tags: ['floor'],
    name: 'Ironing Board',
    thumbnail: '/items/ironing-board/thumbnail.webp',
    src: '/items/ironing-board/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1, 1],
  },

  {
    id: 'coat-rack',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'Coat Rack',
    thumbnail: '/items/coat-rack/thumbnail.webp',
    src: '/items/coat-rack/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.8, 0.5],
  },

  {
    id: 'trash-bin',
    category: 'furniture',
    tags: ['floor'],
    name: 'Trash Bin',
    thumbnail: '/items/trash-bin/thumbnail.webp',
    src: '/items/trash-bin/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.6, 0.5],
  },

  {
    id: 'round-mirror',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Rounded Mirror',
    thumbnail: '/items/round-mirror/thumbnail.webp',
    src: '/items/round-mirror/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 0.1],
    attachTo: 'wall-side',
  },

  {
    id: 'picture',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Picture',
    thumbnail: '/items/picture/thumbnail.webp',
    src: '/items/picture/model.glb',
    scale: [1, 1, 1],
    offset: [0.02, 0.45, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 0.2],
    attachTo: 'wall-side',
  },

  {
    id: 'books',
    category: 'furniture',
    tags: ['countertop', 'decor'],
    name: 'Books',
    thumbnail: '/items/books/thumbnail.webp',
    src: '/items/books/model.glb',
    scale: [1, 1, 1],
    offset: [-0.08, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'column',
    category: 'furniture',
    tags: ['floor', 'structure'],
    name: 'Column',
    thumbnail: '/items/column/thumbnail.webp',
    src: '/items/column/model.glb',
    scale: [1, 1, 1],
    offset: [0, 1.26, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 2.6, 0.5],
  },

  {
    id: 'stairs',
    category: 'furniture',
    tags: ['floor', 'structure'],
    name: 'Stairs',
    thumbnail: '/items/stairs/thumbnail.webp',
    src: '/items/stairs/model.glb',
    scale: [0.61, 0.61, 0.61],
    offset: [0, 0.03, 1.8],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 3.5],
  },

  // {
  //   id: "suspended-fireplace",
  //   category: "furniture",
  //   tags: ["ceiling", "decor"],
  //   name: "Suspended Fireplace",
  //   thumbnail: "/items/suspended-fireplace/thumbnail.webp",
  //   src: "/items/suspended-fireplace/model.glb",
  //   scale: [1, 1, 1],
  //   offset: [0, 0.45, 0],
  //   rotation: [0, 0, 0],
  //   dimensions: [0.5, 0.5, 0.5],
  //   attachTo: "ceiling",
  // },

  {
    id: 'tv-stand',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'TV Stand',
    thumbnail: '/items/tv-stand/thumbnail.webp',
    src: '/items/tv-stand/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.21, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.4, 0.5],
    surface: {
      height: 0.36,
    },
  },

  {
    id: 'shelf',
    category: 'furniture',
    tags: ['wall', 'storage'],
    name: 'Shelf',
    thumbnail: '/items/shelf/thumbnail.webp',
    src: '/items/shelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.1, 0.01],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.7],
    attachTo: 'wall-side',
    surface: {
      height: 0.12,
    },
  },

  {
    id: 'bookshelf',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'Bookshelf',
    thumbnail: '/items/bookshelf/thumbnail.webp',
    src: '/items/bookshelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 0.5],
  },

  {
    id: 'ceiling-lamp',
    category: 'lighting',
    tags: ['ceiling', 'lighting'],
    name: 'Ceiling Lamp',
    thumbnail: '/items/ceiling-lamp/thumbnail.webp',
    src: '/items/ceiling-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.98, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        {
          kind: 'toggle',
          label: 'Power',
          default: true,
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
        {
          kind: 'slider',
          label: 'Color Temp',
          min: 2700,
          max: 6500,
          step: 100,
          unit: 'K',
          default: 4000,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, -0.5, 0],
        },
      ],
    },
  },
  {
    id: 'recessed-light',
    category: 'lighting',
    tags: ['ceiling', 'lighting'],
    name: 'Recessed Light',
    thumbnail: '/items/recessed-light/thumbnail.webp',
    src: '/items/recessed-light/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.094, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        {
          kind: 'toggle',
          label: 'Power',
          default: true,
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
        {
          kind: 'slider',
          label: 'Color Temp',
          min: 2700,
          max: 6500,
          step: 100,
          unit: 'K',
          default: 4000,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, -0.1, 0],
        },
      ],
    },
  },

  {
    id: 'floor-lamp',
    category: 'lighting',
    tags: ['floor', 'lighting'],
    name: 'Floor Lamp',
    thumbnail: '/items/floor-lamp/thumbnail.webp',
    src: '/items/floor-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0.04, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [1, 1.9, 1],
    interactive: {
      controls: [
        {
          kind: 'toggle',
          label: 'Power',
          default: true,
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
        {
          kind: 'slider',
          label: 'Color Temp',
          min: 2700,
          max: 6500,
          step: 100,
          unit: 'K',
          default: 4000,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, 1.4, 0],
        },
      ],
    },
  },

  {
    id: 'table-lamp',
    category: 'lighting',
    tags: ['countertop', 'lighting'],
    name: 'Table Lamp',
    thumbnail: '/items/table-lamp/thumbnail.webp',
    src: '/items/table-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 1],
    interactive: {
      controls: [
        {
          kind: 'toggle',
          label: 'Power',
          default: true,
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
        {
          kind: 'slider',
          label: 'Color Temp',
          min: 2700,
          max: 6500,
          step: 100,
          unit: 'K',
          default: 4000,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 1.5],
          color: '#ffffff',
          offset: [0, 0.65, 0],
        },
      ],
    },
  },

  {
    id: 'closet',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Closet',
    thumbnail: '/items/closet/thumbnail.webp',
    src: '/items/closet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [2, 2.5, 1],
  },

  {
    id: 'dresser',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Dresser',
    thumbnail: '/items/dresser/thumbnail.webp',
    src: '/items/dresser/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.8, 1],
    surface: {
      height: 0.8,
    },
  },

  {
    id: 'bunkbed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Bunkbed',
    thumbnail: '/items/bunkbed/thumbnail.webp',
    src: '/items/bunkbed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.09],
    rotation: [0, 0, 0],
    dimensions: [2, 1.6, 1.5],
  },

  {
    id: 'double-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Double Bed',
    thumbnail: '/items/double-bed/thumbnail.webp',
    src: '/items/double-bed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 2.5],
  },

  {
    id: 'single-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Single Bed',
    thumbnail: '/items/single-bed/thumbnail.webp',
    src: '/items/single-bed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.7, 2.5],
  },

  {
    id: 'sofa',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Sofa',
    thumbnail: '/items/sofa/thumbnail.webp',
    src: '/items/sofa/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.04],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1.5],
  },

  {
    id: 'lounge-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Lounge Chair',
    thumbnail: '/items/lounge-chair/thumbnail.webp',
    src: '/items/lounge-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.09],
    rotation: [0, 0, 0],
    dimensions: [1, 1.1, 1.5],
  },

  {
    id: 'stool',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Stool',
    thumbnail: '/items/stool/thumbnail.webp',
    src: '/items/stool/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1],
  },

  {
    id: 'dining-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Dining Chair',
    thumbnail: '/items/dining-chair/thumbnail.webp',
    src: '/items/dining-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1, 0.5],
  },

  {
    id: 'office-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Office Chair',
    thumbnail: '/items/office-chair/thumbnail.webp',
    src: '/items/office-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0.03],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1],
  },

  {
    id: 'livingroom-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Livingroom Chair',
    thumbnail: '/items/livingroom-chair/thumbnail.webp',
    src: '/items/livingroom-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.8, 1.5],
  },

  {
    id: 'bedside-table',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Bedside Table',
    thumbnail: '/items/bedside-table/thumbnail.webp',
    src: '/items/bedside-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    surface: {
      height: 0.5,
    },
  },

  {
    id: 'coffee-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Coffee Table',
    thumbnail: '/items/coffee-table/thumbnail.webp',
    src: '/items/coffee-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.4, 1.5],
    surface: {
      height: 0.3,
    },
  },

  {
    id: 'office-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Office Table',
    thumbnail: '/items/office-table/thumbnail.webp',
    src: '/items/office-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 1],
    surface: {
      height: 0.75,
    },
  },

  {
    id: 'dining-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Dining Table',
    thumbnail: '/items/dining-table/thumbnail.webp',
    src: '/items/dining-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1],
    surface: {
      height: 0.8,
    },
  },
  {
    id: 'air-conditioner-block',
    category: 'appliance',
    tags: ['floor', 'climate'],
    name: 'Air Conditioner Block',
    thumbnail: '/items/air-conditioner-block/thumbnail.webp',
    src: '/items/air-conditioner-block/model.glb',
    scale: [1, 1, 1],
    offset: [-0.12, 0.28, 0.12],
    rotation: [0, 0, 0],
    dimensions: [1.1, 0.7, 0.8],
  },
  {
    id: 'bean-bag',
    category: 'furniture',
    tags: ['floor', 'seating', 'decor'],
    name: 'Bean Bag',
    thumbnail: '/items/bean-bag/thumbnail.webp',
    src: '/items/bean-bag/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.1, 1.1, 1.1],
  },
  {
    id: 'ceiling-light',
    category: 'lighting',
    tags: ['ceiling', 'lighting'],
    name: 'Ceiling Light',
    thumbnail: '/items/ceiling-light/thumbnail.webp',
    src: '/items/ceiling-light/model.glb',
    scale: [1, 1, 1],
    offset: [0, 1.01, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1, 0.5],
    attachTo: 'ceiling',
  },
  {
    id: 'circular-ceiling-light',
    category: 'lighting',
    tags: ['ceiling', 'lighting'],
    name: 'Circular Ceiling Light',
    thumbnail: '/items/circular-ceiling-light/thumbnail.webp',
    src: '/items/circular-ceiling-light/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.09, 0],
    rotation: [0, 0, 0],
    dimensions: [0.3, 0.1, 0.3],
    attachTo: 'ceiling',
  },
  {
    id: 'couch-medium',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Medium Couch',
    thumbnail: '/items/couch-medium/thumbnail.webp',
    src: '/items/couch-medium/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0.08],
    rotation: [0, 0, 0],
    dimensions: [4.7, 1.9, 2.2],
  },
  {
    id: 'couch-small',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Small Couch',
    thumbnail: '/items/couch-small/thumbnail.webp',
    src: '/items/couch-small/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0.08],
    rotation: [0, 0, 0],
    dimensions: [2.9, 1.9, 2.2],
  },
  {
    id: 'desk',
    category: 'furniture',
    tags: ['floor', 'table', 'storage'],
    name: 'Desk',
    thumbnail: '/items/desk/thumbnail.webp',
    src: '/items/desk/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.03],
    rotation: [0, 0, 0],
    dimensions: [1.8, 0.9, 0.9],
    surface: {
      height: 0.75,
    },
  },
  {
    id: 'door-with-bar',
    category: 'door',
    tags: ['wall'],
    name: 'Door With Bar',
    thumbnail: '/items/door-with-bar/thumbnail.webp',
    src: '/items/door-with-bar/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.6, 2.8, 0.8],
    attachTo: 'wall',
  },
  {
    id: 'doorway-front',
    category: 'door',
    tags: ['wall'],
    name: 'Doorway Front',
    thumbnail: '/items/doorway-front/thumbnail.webp',
    src: '/items/doorway-front/model.glb',
    scale: [2, 2, 2],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 0.5],
    attachTo: 'wall',
  },
  {
    id: 'exercise-bike',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Exercise Bike',
    thumbnail: '/items/exercise-bike/thumbnail.webp',
    src: '/items/exercise-bike/model.glb',
    scale: [1, 1, 1],
    offset: [-0.01, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.4, 0.6],
  },
  {
    id: 'fence',
    category: 'outdoor',
    tags: ['floor', 'fencing'],
    name: 'Fence',
    thumbnail: '/items/fence/thumbnail.webp',
    src: '/items/fence/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 0.1],
  },
  {
    id: 'fire-extinguisher',
    category: 'appliance',
    tags: ['floor', 'safety'],
    name: 'Fire Extinguisher',
    thumbnail: '/items/fire-extinguisher/thumbnail.webp',
    src: '/items/fire-extinguisher/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0.75, 0.1],
    rotation: [0, 0, 0],
    dimensions: [0.3, 1.1, 0.7],
  },
  {
    id: 'flat-screen-tv',
    category: 'appliance',
    tags: ['wall', 'electronics'],
    name: 'Flat Screen TV',
    thumbnail: '/items/flat-screen-tv/thumbnail.webp',
    src: '/items/flat-screen-tv/model.glb',
    scale: [0.5, 0.5, 0.5],
    offset: [0.2, 0.6, 0.02],
    rotation: [0, 0, 0],
    dimensions: [2, 1.2, 0.3],
    attachTo: 'wall-side',
  },
  {
    id: 'freezer',
    category: 'kitchen',
    tags: ['floor', 'large', 'electronics'],
    name: 'Freezer',
    thumbnail: '/items/freezer/thumbnail.webp',
    src: '/items/freezer/model.glb',
    scale: [2, 2, 2],
    offset: [0.43, 0, -0.27],
    rotation: [0, 0, 0],
    dimensions: [0.9, 1.8, 0.6],
  },
  {
    id: 'hedge',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'fencing'],
    name: 'Hedge',
    thumbnail: '/items/hedge/thumbnail.webp',
    src: '/items/hedge/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.5, 1.5],
  },
  {
    id: 'kitchen-fridge',
    category: 'kitchen',
    tags: ['floor', 'large', 'electronics'],
    name: 'Kitchen Fridge',
    thumbnail: '/items/kitchen-fridge/thumbnail.webp',
    src: '/items/kitchen-fridge/model.glb',
    scale: [0.6, 0.6, 0.6],
    offset: [0, 0, -0.04],
    rotation: [0, 0, 0],
    dimensions: [0.8, 2, 0.8],
  },
  {
    id: 'rectangular-mirror',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Rectangular Mirror',
    thumbnail: '/items/rectangular-mirror/thumbnail.webp',
    src: '/items/rectangular-mirror/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.05],
    rotation: [0, 0, 0],
    dimensions: [0.9, 1.6, 0.3],
    attachTo: 'wall-side',
  },
  {
    id: 'sink-cabinet',
    category: 'bathroom',
    tags: ['floor', 'large', 'storage'],
    name: 'Sink Cabinet',
    thumbnail: '/items/sink-cabinet/thumbnail.webp',
    src: '/items/sink-cabinet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.55, 0.02],
    rotation: [0, 0, 0],
    dimensions: [1, 1.3, 0.7],
    surface: {
      height: 0.85,
    },
  },
  {
    id: 'shower',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Shower',
    thumbnail: '/items/shower/thumbnail.webp',
    src: '/items/shower/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.9, 2.1, 0.9],
  },
  {
    id: 'tub',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Tub',
    thumbnail: '/items/tub/thumbnail.webp',
    src: '/items/tub/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.4, 0.8, 1.1],
  },
  {
    id: 'suspended-fireplace',
    category: 'furniture',
    tags: ['ceiling', 'decor'],
    name: 'Suspended Fireplace',
    thumbnail: '/items/suspended-fireplace/thumbnail.webp',
    src: '/items/suspended-fireplace/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0.3],
    rotation: [0, 0, 0],
    dimensions: [1.8, 4.2, 0.8],
    attachTo: 'ceiling',
  },
  {
    id: 'table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Table',
    thumbnail: '/items/table/thumbnail.webp',
    src: '/items/table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.8, 2.8],
    surface: {
      height: 0.8,
    },
  },
  {
    id: 'toilet-brush',
    category: 'bathroom',
    tags: ['floor', 'decor'],
    name: 'Toilet Brush',
    thumbnail: '/items/toilet-brush/thumbnail.webp',
    src: '/items/toilet-brush/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.2, 0.6, 0.2],
  },
  {
    id: 'wall-art-06',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Wall Art',
    thumbnail: '/items/wall-art-06/thumbnail.webp',
    src: '/items/wall-art-06/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.45, 0.02],
    rotation: [0, 0, 0],
    dimensions: [0.6, 0.9, 0.1],
    attachTo: 'wall-side',
  },
  {
    id: 'wall-sink',
    category: 'bathroom',
    tags: ['wall', 'large'],
    name: 'Wall Sink',
    thumbnail: '/items/wall-sink/thumbnail.webp',
    src: '/items/wall-sink/model.glb',
    scale: [1, 1, 1],
    offset: [0, -0.15, 0.3],
    rotation: [0, 0, 0],
    dimensions: [1.4, 1.4, 0.8],
    attachTo: 'wall-side',
  },
  {
    id: 'window-large',
    category: 'window',
    tags: ['wall'],
    name: 'Large Window',
    thumbnail: '/items/window-large/thumbnail.webp',
    src: '/items/window-large/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.83, 0],
    rotation: [0, 3.14, 0],
    dimensions: [1.2, 1.7, 0.2],
    attachTo: 'wall',
  },
  {
    id: 'window-round',
    category: 'window',
    tags: ['wall'],
    name: 'Round Window',
    thumbnail: '/items/window-round/thumbnail.webp',
    src: '/items/window-round/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 3.14, 0],
    dimensions: [0.9, 1.6, 0.3],
    attachTo: 'wall',
  },
  {
    id: 'window-small',
    category: 'window',
    tags: ['wall'],
    name: 'Small Window',
    thumbnail: '/items/window-small/thumbnail.webp',
    src: '/items/window-small/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 3.14, 0],
    dimensions: [0.9, 1.2, 0.3],
    attachTo: 'wall',
  },
  {
    id: 'window-small-2',
    category: 'window',
    tags: ['wall'],
    name: 'Small Window 2',
    thumbnail: '/items/window-small-2/thumbnail.webp',
    src: '/items/window-small-2/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 3.14, 0],
    dimensions: [0.9, 1.2, 0.3],
    attachTo: 'wall',
  },
  {
    id: 'window-square',
    category: 'window',
    tags: ['wall'],
    name: 'Square Window',
    thumbnail: '/items/window-square/thumbnail.webp',
    src: '/items/window-square/model.glb',
    scale: [1, 1, 1],
    offset: [0, 1, 0],
    rotation: [0, 3.14, 0],
    dimensions: [1.6, 2, 0.4],
    attachTo: 'wall',
  },
  {
    id: 'window1-black-open-1731',
    category: 'window',
    tags: ['wall'],
    name: 'Black Open Window',
    thumbnail: '/items/window1-black-open-1731/thumbnail.webp',
    src: '/items/window1-black-open-1731/model.glb',
    scale: [0.5, 0.5, 0.5],
    offset: [0.23, 0.01, -0.22],
    rotation: [0, 3.14, 0],
    dimensions: [1.8, 1.6, 0.9],
    attachTo: 'wall',
  },
  // Life atmosphere baseline pack: generated by tooling/assets/generate-life-atmosphere-assets.mjs.
  {
    id: 'person-standing-adult',
    category: 'furniture',
    tags: ['floor', 'people', 'scale-reference'],
    name: 'Standing Adult',
    thumbnail: '/items/person-standing-adult/thumbnail.webp',
    src: '/items/person-standing-adult/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.55, 1.75, 0.45],
  },
  {
    id: 'person-standing-casual',
    category: 'furniture',
    tags: ['floor', 'people', 'scale-reference'],
    name: 'Casual Person',
    thumbnail: '/items/person-standing-casual/thumbnail.webp',
    src: '/items/person-standing-casual/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.55, 1.68, 0.45],
  },
  {
    id: 'person-walking',
    category: 'furniture',
    tags: ['floor', 'people', 'scale-reference'],
    name: 'Walking Person',
    thumbnail: '/items/person-walking/thumbnail.webp',
    src: '/items/person-walking/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.75, 1.72, 0.55],
  },
  {
    id: 'person-seated',
    category: 'furniture',
    tags: ['floor', 'people', 'seating', 'scale-reference'],
    name: 'Seated Person',
    thumbnail: '/items/person-seated/thumbnail.webp',
    src: '/items/person-seated/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.7, 1.22, 0.8],
  },
  {
    id: 'person-child',
    category: 'furniture',
    tags: ['floor', 'people', 'kids', 'scale-reference'],
    name: 'Child',
    thumbnail: '/items/person-child/thumbnail.webp',
    src: '/items/person-child/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.45, 1.15, 0.35],
  },
  {
    id: 'person-wheelchair',
    category: 'furniture',
    tags: ['floor', 'people', 'accessibility', 'scale-reference'],
    name: 'Wheelchair User',
    thumbnail: '/items/person-wheelchair/thumbnail.webp',
    src: '/items/person-wheelchair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.85, 1.25, 0.9],
  },
  {
    id: 'person-service-staff',
    category: 'furniture',
    tags: ['floor', 'people', 'commercial', 'scale-reference'],
    name: 'Service Staff',
    thumbnail: '/items/person-service-staff/thumbnail.webp',
    src: '/items/person-service-staff/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.55, 1.72, 0.45],
  },
  {
    id: 'person-office-worker',
    category: 'furniture',
    tags: ['floor', 'people', 'office', 'scale-reference'],
    name: 'Office Worker',
    thumbnail: '/items/person-office-worker/thumbnail.webp',
    src: '/items/person-office-worker/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.6, 1.72, 0.45],
  },
  {
    id: 'people-pair',
    category: 'furniture',
    tags: ['floor', 'people', 'scale-reference'],
    name: 'People Pair',
    thumbnail: '/items/people-pair/thumbnail.webp',
    src: '/items/people-pair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.05, 1.75, 0.55],
  },
  {
    id: 'people-family',
    category: 'furniture',
    tags: ['floor', 'people', 'kids', 'scale-reference'],
    name: 'Family Group',
    thumbnail: '/items/people-family/thumbnail.webp',
    src: '/items/people-family/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.45, 1.75, 0.75],
  },
  {
    id: 'dog-standing',
    category: 'furniture',
    tags: ['floor', 'animal', 'pet'],
    name: 'Standing Dog',
    thumbnail: '/items/dog-standing/thumbnail.webp',
    src: '/items/dog-standing/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.8, 0.55, 0.35],
  },
  {
    id: 'cat-sitting',
    category: 'furniture',
    tags: ['floor', 'animal', 'pet'],
    name: 'Sitting Cat',
    thumbnail: '/items/cat-sitting/thumbnail.webp',
    src: '/items/cat-sitting/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.35, 0.42, 0.35],
  },
  {
    id: 'rabbit-sitting',
    category: 'outdoor',
    tags: ['floor', 'animal', 'pet', 'garden'],
    name: 'Sitting Rabbit',
    thumbnail: '/items/rabbit-sitting/thumbnail.webp',
    src: '/items/rabbit-sitting/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.35, 0.42, 0.35],
  },
  {
    id: 'bird-on-perch',
    category: 'furniture',
    tags: ['countertop', 'animal', 'pet', 'decor'],
    name: 'Bird On Perch',
    thumbnail: '/items/bird-on-perch/thumbnail.webp',
    src: '/items/bird-on-perch/model.glb',
    scale: [1, 1, 1],
    grounding: 'none',
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.32, 0.55, 0.32],
  },
  {
    id: 'fish-tank',
    category: 'furniture',
    tags: ['countertop', 'animal', 'pet', 'decor'],
    name: 'Fish Tank',
    thumbnail: '/items/fish-tank/thumbnail.webp',
    src: '/items/fish-tank/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.9, 0.55, 0.35],
  },
  {
    id: 'duck-standing',
    category: 'outdoor',
    tags: ['floor', 'animal', 'garden'],
    name: 'Duck',
    thumbnail: '/items/duck-standing/thumbnail.webp',
    src: '/items/duck-standing/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.45, 0.45, 0.7],
  },
  {
    id: 'deer-garden',
    category: 'outdoor',
    tags: ['floor', 'animal', 'garden'],
    name: 'Garden Deer',
    thumbnail: '/items/deer-garden/thumbnail.webp',
    src: '/items/deer-garden/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.8, 1.05, 0.35],
  },
  {
    id: 'horse-standing',
    category: 'outdoor',
    tags: ['floor', 'animal', 'garden'],
    name: 'Standing Horse',
    thumbnail: '/items/horse-standing/thumbnail.webp',
    src: '/items/horse-standing/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.8, 1.55, 0.55],
  },
  {
    id: 'indoor-ficus',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation', 'indoor'],
    name: 'Indoor Ficus',
    thumbnail: '/items/indoor-ficus/thumbnail.webp',
    src: '/items/indoor-ficus/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.75, 1.55, 0.75],
  },
  {
    id: 'indoor-monstera',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation', 'indoor'],
    name: 'Indoor Monstera',
    thumbnail: '/items/indoor-monstera/thumbnail.webp',
    src: '/items/indoor-monstera/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.85, 1.15, 0.85],
  },
  {
    id: 'indoor-snake-plant',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation', 'indoor'],
    name: 'Snake Plant',
    thumbnail: '/items/indoor-snake-plant/thumbnail.webp',
    src: '/items/indoor-snake-plant/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.45, 1, 0.45],
  },
  {
    id: 'indoor-palm-tall',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation', 'indoor'],
    name: 'Tall Indoor Palm',
    thumbnail: '/items/indoor-palm-tall/thumbnail.webp',
    src: '/items/indoor-palm-tall/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.9, 1.9, 0.9],
  },
  {
    id: 'tabletop-succulent',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation', 'indoor'],
    name: 'Tabletop Succulent',
    thumbnail: '/items/tabletop-succulent/thumbnail.webp',
    src: '/items/tabletop-succulent/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.22, 0.28, 0.22],
  },
  {
    id: 'tabletop-flower-vase',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation', 'indoor'],
    name: 'Flower Vase',
    thumbnail: '/items/tabletop-flower-vase/thumbnail.webp',
    src: '/items/tabletop-flower-vase/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.3, 0.65, 0.3],
  },
  {
    id: 'hanging-planter',
    category: 'furniture',
    tags: ['ceiling', 'decor', 'vegetation', 'indoor'],
    name: 'Hanging Planter',
    thumbnail: '/items/hanging-planter/thumbnail.webp',
    src: '/items/hanging-planter/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.45, 0.7, 0.45],
    attachTo: 'ceiling',
  },
  {
    id: 'wall-planter',
    category: 'furniture',
    tags: ['wall', 'decor', 'vegetation', 'indoor'],
    name: 'Wall Planter',
    thumbnail: '/items/wall-planter/thumbnail.webp',
    src: '/items/wall-planter/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.25, 0.08],
    rotation: [0, 0, 0],
    dimensions: [0.75, 0.5, 0.2],
    attachTo: 'wall-side',
  },
  {
    id: 'planter-box',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Planter Box',
    thumbnail: '/items/planter-box/thumbnail.webp',
    src: '/items/planter-box/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.2, 0.65, 0.4],
  },
  {
    id: 'terrace-planter-set',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Terrace Planter Set',
    thumbnail: '/items/terrace-planter-set/thumbnail.webp',
    src: '/items/terrace-planter-set/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.4, 0.95, 0.55],
  },
  {
    id: 'round-shrub',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Round Shrub',
    thumbnail: '/items/round-shrub/thumbnail.webp',
    src: '/items/round-shrub/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.9, 0.8, 0.9],
  },
  {
    id: 'flowering-bush',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Flowering Bush',
    thumbnail: '/items/flowering-bush/thumbnail.webp',
    src: '/items/flowering-bush/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.75, 0.85],
  },
  {
    id: 'grass-clump',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Grass Clump',
    thumbnail: '/items/grass-clump/thumbnail.webp',
    src: '/items/grass-clump/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.6, 0.45, 0.6],
  },
  {
    id: 'groundcover-patch',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Groundcover Patch',
    thumbnail: '/items/groundcover-patch/thumbnail.webp',
    src: '/items/groundcover-patch/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.2, 0.25, 0.7],
  },
  {
    id: 'rectangular-flower-bed',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Flower Bed',
    thumbnail: '/items/rectangular-flower-bed/thumbnail.webp',
    src: '/items/rectangular-flower-bed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.8, 0.45, 0.8],
  },
  {
    id: 'hedge-row',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'fencing', 'garden'],
    name: 'Hedge Row',
    thumbnail: '/items/hedge-row/thumbnail.webp',
    src: '/items/hedge-row/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.9, 0.45],
  },
  {
    id: 'hedge-corner',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'fencing', 'garden'],
    name: 'Hedge Corner',
    thumbnail: '/items/hedge-corner/thumbnail.webp',
    src: '/items/hedge-corner/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.2, 0.9, 1.2],
  },
  {
    id: 'small-ornamental-tree',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Small Ornamental Tree',
    thumbnail: '/items/small-ornamental-tree/thumbnail.webp',
    src: '/items/small-ornamental-tree/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2.2, 1],
  },
  {
    id: 'shade-tree',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Shade Tree',
    thumbnail: '/items/shade-tree/thumbnail.webp',
    src: '/items/shade-tree/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.8, 3.2, 1.8],
  },
  {
    id: 'cypress-tree',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Cypress Tree',
    thumbnail: '/items/cypress-tree/thumbnail.webp',
    src: '/items/cypress-tree/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.75, 2.8, 0.75],
  },
  {
    id: 'bamboo-cluster',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Bamboo Cluster',
    thumbnail: '/items/bamboo-cluster/thumbnail.webp',
    src: '/items/bamboo-cluster/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.85, 2.3, 0.85],
  },
  {
    id: 'banana-plant',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Banana Plant',
    thumbnail: '/items/banana-plant/thumbnail.webp',
    src: '/items/banana-plant/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.2, 2.1, 1.2],
  },
  {
    id: 'tall-garden-planter',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Tall Garden Planter',
    thumbnail: '/items/tall-garden-planter/thumbnail.webp',
    src: '/items/tall-garden-planter/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.6, 1.15, 0.6],
  },
  {
    id: 'entry-planter-pair',
    category: 'outdoor',
    tags: ['floor', 'vegetation', 'garden'],
    name: 'Entry Planter Pair',
    thumbnail: '/items/entry-planter-pair/thumbnail.webp',
    src: '/items/entry-planter-pair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.6, 1.2, 0.55],
  },
  // End life atmosphere baseline pack.
]

const CATEGORY_TAG_FILTERS = {
  people: 'people',
  plants: 'vegetation',
  animals: 'animal',
} as const

const CATEGORY_HIDDEN_TAGS = {
  people: ['people'],
  plants: ['vegetation'],
  animals: ['animal'],
} as const

const CATEGORY_PROMOTED_IDS = {
  people: [
    'person-standing-adult',
    'person-standing-casual',
    'person-walking',
    'person-seated',
    'person-child',
    'person-wheelchair',
    'person-service-staff',
    'person-office-worker',
    'people-pair',
    'people-family',
  ],
  plants: [
    'indoor-ficus',
    'indoor-monstera',
    'indoor-snake-plant',
    'indoor-palm-tall',
    'tabletop-succulent',
    'tabletop-flower-vase',
    'hanging-planter',
    'wall-planter',
    'planter-box',
    'terrace-planter-set',
    'round-shrub',
    'flowering-bush',
    'grass-clump',
    'groundcover-patch',
    'rectangular-flower-bed',
    'hedge-row',
    'hedge-corner',
    'small-ornamental-tree',
    'shade-tree',
    'cypress-tree',
    'bamboo-cluster',
    'banana-plant',
    'tall-garden-planter',
    'entry-planter-pair',
  ],
  animals: [
    'dog-standing',
    'cat-sitting',
    'rabbit-sitting',
    'bird-on-perch',
    'fish-tank',
    'duck-standing',
    'deer-garden',
    'horse-standing',
  ],
} as const

export function getCatalogItemsForCategory(category: string | null | undefined): AssetInput[] {
  if (!category) return []

  const tagFilter = CATEGORY_TAG_FILTERS[category as keyof typeof CATEGORY_TAG_FILTERS]
  if (!tagFilter) {
    return CATALOG_ITEMS.filter((item) => item.category === category)
  }

  const promotedIds = CATEGORY_PROMOTED_IDS[category as keyof typeof CATEGORY_PROMOTED_IDS] ?? []
  const promotedIndex = new Map<string, number>(promotedIds.map((id, index) => [id, index]))

  return CATALOG_ITEMS.filter((item) => item.tags?.includes(tagFilter)).sort((left, right) => {
    const leftRank = promotedIndex.get(left.id)
    const rightRank = promotedIndex.get(right.id)

    if (leftRank !== undefined || rightRank !== undefined) {
      if (leftRank === undefined) return 1
      if (rightRank === undefined) return -1
      if (leftRank !== rightRank) return leftRank - rightRank
    }

    return left.name.localeCompare(right.name)
  })
}

export function getCatalogItemById(id: string | null | undefined): AssetInput | null {
  if (!id) return null
  return CATALOG_ITEMS.find((item) => item.id === id) ?? null
}

export function getCatalogHiddenTags(category: string | null | undefined): Set<string> {
  const tags = CATEGORY_HIDDEN_TAGS[category as keyof typeof CATEGORY_HIDDEN_TAGS]
  return new Set(tags ?? [])
}

export function getDefaultCatalogItem(category: string | null | undefined): AssetInput | null {
  return getCatalogItemsForCategory(category)[0] ?? null
}
